# Generated by Django 4.1.6 on 2023-02-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distri_name', models.CharField(max_length=20, unique=True)),
                ('distri_addr', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, unique=True)),
                ('brand_desc', models.CharField(max_length=300)),
                ('brand_cat', models.CharField(max_length=20)),
                ('brnad_distri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.distributor')),
            ],
        ),
    ]
